name: container
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        dotnet-version: [3.1.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Compile binaries
      run: |
        dotnet restore 
        dotnet build ./ccclient/ccclient.csproj -r ubuntu-x64
        dotnet test -r ubuntu-x64

    - name: Build container image
      run: |
        docker build -t gluwa/container-under-test ccclient/bin/Debug/netcoreapp3.1/ubuntu-x64/

    - name: Run container and wait until healthy
      run: |
        docker run -t --name container-under-test gluwa/container-under-test tail > /dev/null &
        sleep 15
        COUNT=0
        while [ "`docker inspect -f {{.State.Health.Status}} container-under-test`" != "healthy" ] && [ $COUNT -lt 20 ]; do let "COUNT++"; echo "Checking health status - Attempt $COUNT of 20"; sleep 15; done
        if [ $COUNT -ge 20 ]; then exit 1; fi

    - name: Kill and remove container
      run: |
        docker kill container-under-test
        docker rm -f container-under-test
