name: .NET

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Docker Build
      run: docker build ./ccclient -t gluwa/container-under-test

    - name: Run container and wait until healthy
      run: |
        docker run -t --name container-under-test gluwa/container-under-test tail > /dev/null &
        sleep 15
        COUNT=0
        while [ "`docker inspect -f {{.State.Health.Status}} container-under-test`" != "healthy" ] && [ $COUNT -lt 20 ]; do COUNT=$((COUNT+1)); echo "Checking health status - Attempt $COUNT of 20"; sleep 15; done
        if [ $COUNT -ge 20 ]; then echo "Error - Failed to verify healthcheck after 5 minutes"; exit 1; else echo "Successfully verified healthcheck!"; fi

    - name: Kill and remove container
      run: |
        docker kill container-under-test
        docker rm -f container-under-test
